version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 8000:8000
    ports:
      - 8000:8000
    volumes:
      - ./myapp:/djangocrm/mydata

volumes:
  myapp:

